name: local_hero
description: A widget which implicitly launches a hero animation when its position changed within the same route.
version: 0.1.0
homepage: https://github.com/letsar/local_hero

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
